# Generated by Django 3.0.7 on 2020-06-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0007_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='static/', verbose_name='Изображение книги'),
        ),
    ]
